---
name: Виктор
surname: Аврамов
position: "Главен асистент"
address: "Департамент „Администрация и управление“, Нов български университет"
phone: +359 877 985 179
www: vavramov.com
profilepic: photo.jpg
email: "vavramov@nbu.bg"
twitter: victorstavramov
github: quantumjazz
linkedin: victor-avramov-ba1110b1
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Работа
## Настояща
```{r}
library(tibble)
tribble(
  ~title, ~unit, ~startMonth, ~startYear, ~endMonth, ~endYear, ~where, ~detail,
     "Ръководител", "Учебно практическо изследователско звено „Количествени методи и моделиране“", "Октомври", 2019, "", NA, "Нов български университет", "идентифициране, анализ и управление на рискове",
     "Ръководител", "Учебно практическо изследователско звено „Количествени методи и моделиране“", "Октомври", 2019, "", NA, "Нов български университет", "анализ на макроикономически процеси",
     "Ръководител", "Учебно практическо изследователско звено „Количествени методи и моделиране“", "Октомври", 2019, "", NA, "Нов български университет", "анализ на пазари и пазарни структури",
     "Ръководител", "Учебно практическо изследователско звено „Количествени методи и моделиране“", "Октомври", 2019, "", NA, "Нов български университет", "оптимизиране на бизнес процеси",
      "Ръководител", "Учебно практическо изследователско звено „Количествени методи и моделиране“", "Октомври", 2019, "", NA, "Нов български университет", "създаване на помощни инструменти за управление на компани",
     "Директор", "Програмен съвет към Департамент „Администрация и управление“", "Януари", 2019, "", NA, "Нов български университет", "координиране и участие в процедурите по акредитация на учебните програми към Департамент „Администрация и управление“",
     "Директор", "Програмен съвет към Департамент „Администрация и управление“", "Януари", 2019, "", NA, "Нов български университет", "подпомагане на учебния процес",
     "Директор", "Програмен съвет към Департамент „Администрация и управление“", "Януари", 2019, "", NA, "Нов български университет", "осигуряване на качеството на учебните програми, включително адаптиране и промяна на съществуващи и създаване на нови програми",
     "Директор", "Програмен съвет към Департамент „Администрация и управление“", "Януари", 2019, "", NA, "Нов български университет", "координиране и контролиране на дейността на програмните консултанти (тя се състои основно в консултиране на студенти по административни и академични въпроси, създаване на индивидуални учебни програми и подпомагане на ориентацията им)",
     "Главен асистент", "Департамент „Администрация и управление“", "Юли", 2014, "", NA, "Нов български университет", "преподаване, оценяване, развиване на съдържанието на курсове в Moodle",
     "Главен асистент", "Департамент „Администрация и управление“", "Юли", 2014, "", NA, "Нов български университет", "популяризиране на учебните програми в и извън кандидат-студентски кампании",
     "Главен асистент", "Департамент „Администрация и управление“", "Юли", 2014, "", NA, "Нов български университет", "основни курсове: Теория на организацията, Индустриална организация,  Принципи на мениджмънта, Управление на промените, Проектиране на управленски системи, Изкуството на преговорите и др.",
) %>% 
  detailed_entries(
    with = title,
    what = unit,
    why = detail,
    when = glue::glue("{startMonth} {startYear} -- {endMonth} {endYear}",.na = ""),
    where = where
  )
```

## Предишна 

```{r}
library(tibble)
tribble(
  ~title, ~unit, ~startMonth, ~startYear, ~endMonth, ~endYear, ~where, ~detail,
  "Главен експерт", "Комисия за енергийно и водно регулиране", "Януари", 2020, "Май", 2021, "София - България", "участие в проучвания и проверки за нарушение на чл. 3 и/или 5 от Регламент (ЕС) № 1227/2011, анализ на пазарни данни (цени, количества, сключени сделки) на пазара на едро на електрическа енергия",
   "Главен експерт", "Комисия за енергийно и водно регулиране", "Януари", 2020, "Май", 2021, "София - България", "Изработване на икономически експертни анализи и оценки, становища, свързани с осъществяването на мониторинг на пазара на едро",
   "Експерт/член", "Център за анализи и управление на рискове", "Октомври", 2013, "Август", 2019, "Нов български университет", "идентифициране и анализиране на рискове в енергийния сектор (електроенергетика, природен газ, течни горива)",
   "Експерт/член", "Център за анализи и управление на рискове", "Октомври", 2013, "Август", 2019, "Нов български университет", "предлагане на управленски мерки за въздействие върху рискове",
   "Експерт/член", "Център за анализи и управление на рискове", "Октомври", 2013, "Август", 2019, "Нов български университет", "прогнозиране на потреблението на електрическа енергия",
   "Експерт/член", "Център за анализи и управление на рискове", "Октомври", 2013, "Август", 2019, "Нов български университет", "пазарни анализи",
   "Експерт/член", "Център за анализи и управление на рискове", "Октомври", 2013, "Август", 2019, "Нов български университет", "управление/участие в проекти",
    "Експерт/член", "Център за анализи и управление на рискове", "Октомври", 2013, "Август", 2019, "Нов български университет", "изготвяне на периодични и извънредни доклади за сектора, статии, студии",
       "Асистент", "Департамент „Администрация и управление“", "Ноември", 2012, "Август", 2014, "Нов български университет", "преподаване, оценяване, развиване на съдържанието на курсове в Moodle",
     "Асистент", "Департамент „Администрация и управление“", "Ноември", 2012, "Август", 2014, "Нов български университет", "популяризиране на учебните програми в и извън кандидат-студентски кампании",
     "Асистент", "Департамент „Администрация и управление“", "Ноември", 2012, "Август", 2014, "Нов български университет", "основни курсове: Теория на организацията, Управление на проекти,  Бизнес етика, Управление на промените, Проектиране на управленски системи, Изкуството на преговорите и др",
    "Програмен консултант", "Програмен съвет към Департамент „Администрация и управление“", "Ноември", 2012, "Декември", 2018, "Нов български университет", "подпомагане на учебния процес",
     "Програмен консултант", "Програмен съвет към Департамент „Администрация и управление“", "Ноември", 2012, "Декември", 2018, "Нов български университет", "осигуряване на качеството на учебните програми, включително адаптиране и промяна на съществуващи и създаване на нови програми",
     "Програмен консултант", "Програмен съвет към Департамент „Администрация и управление“", "Ноември", 2012, "Декември", 2018, "Нов български университет", "консултиране на студенти по административни и академични въпроси, създаване на индивидуални учебни програми и подпомагане на ориентацията им",
  "Програмен консултант", "Програмен съвет към Департамент „Администрация и управление“", "Ноември", 2012, "Декември", 2018, "Нов български университет", "участие в процедурите по акредитация на учебни програми",
    "Локален асистент/анализатор", "Европейски парламент", "Февруари", 2012, "Август", 2014, "София, България", "анализ на политики, консултиране, прогнозиране",
    "Локален асистент/анализатор", "Европейски парламент", "Февруари", 2012, "Август", 2014, "София, България", "организиране/участие в работни комисии, конференции, семинари",
    "Координатор", "Политическа партия „Демократи за силна България”", "Януари", 2006, "Август", 2009, "София, България", "изследване и анализи в областта на енергийната политика",
    "Координатор", "Политическа партия „Демократи за силна България”", "Януари", 2006, "Август", 2009, "София, България", "участие в дейността на вътрешната комисия по енергийна политика",
    "Координатор", "Политическа партия „Демократи за силна България”", "Януари", 2006, "Август", 2009, "София, България", "осъществяване на контакти с вътрешни и външни за ПП ДСБ партньори, в това число: EUFORES, ПАСЕ, Министерство на икономиката и енергетиката и др.",
    "Координатор", "Политическа партия „Демократи за силна България”", "Януари", 2006, "Август", 2009, "София, България", "подготовка и участие в политически събития: конференции, семинари, кръгли маси, обучения",
    "Координатор", "Политическа партия „Демократи за силна България”", "Януари", 2006, "Август", 2009, "София, България", "•	подготовка и участие в организирането на предизборни кампании, в това число: президентски, местни избори; избори за национален и европейски парламент",
    "Стажант", "Министерство на регионалното развитие и благоустройството", "Май", 2002, "Юни", 2002, "София, България", "работа с проектна документация по програмата ФАР-Трансгранично сътрудничество",
) %>% 
  detailed_entries(
    with = title,
    what = unit,
    why = detail,
    when = glue::glue("{startMonth} {startYear} -- {endMonth} {endYear}",.na = ""),
    where = where
  )
```
\

# Образование

```{r education}
tribble(
  ~ degree, ~ uni, ~ loc, ~ dates, ~ details,
  "Доктор по политически науки", "Софийски университет „Св. Климент Охридски”", "София, България", "2007--2012", 
    list("Тема на дисертацията: “Процесът на изработване на енергийната политика на Европейския съюз: актьори, комуникация и взаимодействие“"),
  "Магистър по публична администрация", "Софийски университет „Св. Климент Охридски”", "София, България", "2002 -- 2004", 
    list("Тема на дипломната работа: „Концепцията за бюрокрацията на Макс Вебер и дискурсът за публичната администрация през 20 в.”"),
  "Бакалавър по публична администрация", "Софийски университет „Св. Климент Охридски”", "София, България", "1998 -- 2002", 
  list("Основни курсове: Статистика, Изследователски методи, Теория на организацията, Информационни системи")
) %>% 
  detailed_entries(degree, dates, uni, loc, details)
```

# Специализации в областта на експертиза

```{r}
tribble(
  ~area, ~accomplishment, ~year, ~where,
  "Международна програма за лидери (IVLP)", "Държавен департамент на САЩ", "Юни 2019", "САЩ",
  "Програма за обучение и диалог на международна делегация на енергийни експерти", "Фондация „Конрад Аденауер“", "Октомври 2014", "Федерална република Германия",
  "Специализация, финансирана от фондация „Конрад Аденауер“ на тема „Енергийни политики и политики, свързани с климатичните промени: политики, комуникация и взаимодействие“", "Фондация „Конрад Аденауер“", "Април -- Август 2010", "Universität Trier, Германия"
  
) %>% 
  detailed_entries(
    with = area,
    what = accomplishment,
    when = year,
    where = where
  )
```

# Избрани публикации

```{r publications}
bibliography_entries("publications.bib", "Publications")
```

# Избрани участия в медиите

```{r}
tribble(
  ~area, ~accomplishment, ~year, ~where,
    "Миньорите изпитват несигурност относно държавната политика в енергетиката", "https://www.bnr.bg/post/101051614/viktor-avramov-minyorite-izpitvat-nesigurnost-otnosno-darjavnata-politika-v-energetikata", "29.11.2018", "БНР",
  "Виктор Аврамов с коментар за сценариите около АЕЦ Белене", "https://www.bloombergtv.bg/video/viktor-avramov-s-komentar-za-stsenariite-okolo-aets-belene", "07.06.2018", "Bloomberg TV Bulgaria",
  "Виктор Аврамов с коментар по енергийни теми от външно и вътрешно естество", "https://www.bloombergtv.bg/video/viktor-avramov-s-komentar-po-energiyni-temi-ot-vanshno-i-vatreshno-estestvo", "12.12.2017", "Bloomberg TV Bulgaria",
  "Виктор Аврамов с коментар за очакваните санкции по оста САЩ-Русия", "http://www.bloombergtv.bg/video/viktor-avramov-s-komentar-za-ochakvanite-sanktsii-po-osta-sasht-rusiya", "26.07.2017", "Bloomberg TV Bulgaria",
  "Има ли забранени думи при успешните преговори за коалиция?", "http://m.btvnovinite.bg/article/bulgaria/ima-li-zabraneni-dumi-pri-uspeshnite-pregovori-za-koalicija.html", "08.04.2017", "bTV News",
  "Виктор Аврамов за решението на КЗК", "http://www.bloombergtv.bg/video/viktor-avramov-za-reshenieto-na-kzk", "29.03.2017", "Bloomberg TV Bulgaria",
  "Относно енергийната бедност и енергийната ефективност", "http://www.bloombergtv.bg/video/dragomir-tsanev-i-viktor-avramov-za-energiynata-efektivnost", "09.12.2016", "Bloomberg TV Bulgaria",
) %>% 
  detailed_entries(
    with = area,
    what = accomplishment,
    when = year,
    where = where
  )
```

# Умения
## Технически

```{r techtable}
tribble(
   ~`Езици за програмиране`, ~Софтуер, ~Други,
  "R -- Python -- Matlab",
  "RStudio -- Excel -- Lyx -- Mendeley",
  "Linux -- Git -- Markdown -- LaTex"
) %>%
  kableExtra::kable(booktabs = T, align = 'c', escape = F, format = "latex") %>%
  kableExtra::kable_styling(full_width = F, font_size = 9, latex_options = "hold_position") %>% 
  kableExtra::row_spec(0, bold = T, color = "#009acd") %>% 
  kableExtra::row_spec(1, bold = F, color = "#7f7f7f") %>% 
  kableExtra::column_spec(column = 1:3, width = '4.75cm')
```

## Езици

```{r langforeign, results='markup'}
data.frame(
  Skill = c("Reading", "Writing", "Listening","Speaking"),
  Български = kableExtra::cell_spec(c(rep("Native", 4)), 'latex', color = '#005c7b'), 
  Английски = kableExtra::cell_spec(c("C1","C1","C1","C1"), 'latex', color = '#009acd'), 
  Немски = kableExtra::cell_spec(c("B1","B1","B1","B1"), 'latex', color = '#7fcce6'), 
  Руски = kableExtra::cell_spec(c("B2","B2","B2","B2"), 'latex', color = '#4cb8dc')
) %>%
  kableExtra::kable(booktabs = T, align = 'c', escape = F, format = "latex") %>%
  kableExtra::kable_styling(full_width = F, font_size = 9, latex_options = "hold_position") %>% 
  kableExtra::footnote(
    footnote_as_chunk = T,
    general_title = " ",
    general = "\\\\tiny Common European Framework of Reference for Languages: A1/A2: Basic User. B1/B2: Independent User. C1/C2: Proficient User",
    escape = F
  ) %>%
  kableExtra::column_spec(column = 1:6, width = '2.4cm')
```

